// complete filename

var wordListArray = new Array(
'English_MLB_Teams.txt',
'English_NBA_Teams.txt',
'English_NFL_Teams.txt',
'English_NHL_Teams.txt',
'English_African_Deities.txt',
'English_Celtic_Deities.txt',
'English_Egyptian_Deities.txt',
'English_Greek_Deities.txt',
'English_Norse_Deities.txt',
'English_Roman_Deities.txt',
'English_Baseball.txt',
'English_Basketball.txt',
'English_Hockey.txt',
'English_USA_Football.txt',
'English_Constellations.txt',
'English_Elements.txt',
'English_HTML_Colors.txt',
'English_USA_Capitals.txt',
'English_USA_States.txt',
'Family_Names.txt',
'Female_Names.txt',
'Given_Names.txt',
'Male_Names.txt',
'English_WOTD_2000.txt',
'English_WOTD_2001.txt',
'English_WOTD_2002.txt',
'English_WOTD_2003.txt',
'English_WOTD_2004.txt',
'English_WOTD_2005.txt'
);
